GET http://localhost:8080/api/time
Content-Type: */*

###

GET http://localhost:8080/api/books

###

POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "The Hobbit",
  "author": "J.R.R. Tolkien"
}